// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdRYhzJ6D6tAjfB42y34qgOLHp0Mm5GQ',
    appId: '1:767485551383:android:0ec8a04674a024cc4b0d52',
    messagingSenderId: '767485551383',
    projectId: 'pulse-b9de9',
    storageBucket: 'pulse-b9de9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpR4uLamGwqZI1Yg48Fh7cDJcB9_MdNAw',
    appId: '1:767485551383:ios:eb584559bd4b1e314b0d52',
    messagingSenderId: '767485551383',
    projectId: 'pulse-b9de9',
    storageBucket: 'pulse-b9de9.firebasestorage.app',
    androidClientId: '767485551383-26qu7eq7j82i0ecv63gsvogp32o3p674.apps.googleusercontent.com',
    iosClientId: '767485551383-m48e1evhi81jkaaume7sf06n6dvps013.apps.googleusercontent.com',
    iosBundleId: 'com.example.nabd',
  );
}
